---
  title: "Weebo BackStage"
  date: 2019-01-20
---
    theme: minima
    title: Weebo BackStage
    author: CyberExplosion
    email: minhkhoi632000@gmail.com
    description: > # this means to ignore newlines until "baseurl:"
    This is a place for me to record my daily activities as well as things I want
    to share. This is no place for open discussion or under any rules but mine
    alone. Posts from here will be under my judgement and based on my opinion alone.
    Nothing in here shall and never be used as personal attack against anybody.
    (Typical as it maybe, this web sole purpose is just to allow me to have a place
    to rant about my sad life, therefore no one should even be bother to look into
    this for any gains :pray:)

    # social links
    twitter_username: GT_Explosion
    github_username:  CyberExplosion

    show_excerpts: true # set to false to remove excerpts on the homepage
